Repository BJReplay/ha-solcast-solar, pull requests merged in 2025-04, with the labels that each got.

#266 Fix remove orphaned cache where key has non-alpha chars
  README.md
  custom_components/solcast_solar/solcastapi.py
Labels: bug

#268 Create pt.json
  custom_components/solcast_solar/translations/pt.json
Labels: translation, thanks!

#279 Update TEMPLATES.md
  .github/SCREENSHOTS/example_span_offset_modifier.png
  TEMPLATES.md
Labels: documentation
